("MIS.DGO"
 (;; libsm64: racer prefix — standard 8-file set every racer DGO opens with.
  "target-racer-h.o"
  "racer-part.o"
  "racer.o"
  "target-racer.o"
  "racer-states.o"
  "collide-reaction-racer.o"
  "eichar-racer+0-ag.go"
  "tpage-1119.go"
  ;; libsm64: lurker-crab code + art group so sm64-crab-shell (mario.gc)
  ;; can render Mario's shell visual on this racer level.  Code binds
  ;; *lurkercrab-sg* + def-art-elt slots; art-group carries the
  ;; skeleton / joints / animations.  Beach's texture tiles are mirrored
  ;; into this level's fr3 by extract_from_level (decompiler), so we
  ;; skip the beach tpage-212..215 files here — they're 1.4 MB +
  ;; ~700 KB combined and blow the per-level DGO heap if included.
  "lurkercrab.o"
  "lurkercrab-ag.go"
  "battlecontroller.o"
  "mistycannon.o"
  "babak-with-cannon.o"
  "blocking-plane.o"
  "misty-obs.o"
  "misty-warehouse.o"
  "misty-conveyor.o"
  "mud.o"
  "muse.o"
  "bonelurker.o"
  "quicksandlurker.o"
  "misty-teetertotter.o"
  "balloonlurker.o"
  "misty-part.o"
  "sidekick-human.o"
  "tpage-516.go"
  "tpage-521.go"
  "tpage-518.go"
  "tpage-520.go"
  "babak-ag.go"
  "balloonlurker-ag.go"
  "boatpaddle-ag.go"
  "bonelurker-ag.go"
  "breakaway-left-ag.go"
  "breakaway-mid-ag.go"
  "breakaway-right-ag.go"
  "darkecocan-ag.go"
  "ef-plane-ag.go"
  "keg-ag.go"
  "keg-conveyor-ag.go"
  "keg-conveyor-paddle-ag.go"
  "mis-bone-bridge-ag.go"
  "mis-bone-platform-ag.go"
  "mistycam-ag.go"
  "mistycannon-ag.go"
  "muse-ag.go"
  "orb-cache-top-ag.go"
  "plat-eco-ag.go"
  "quicksandlurker-ag.go"
  "racer-ag.go"
  "ropebridge-36-ag.go"
  "rounddoor-ag.go"
  "sack-ag.go"
  "sharkey-ag.go"
  "sidekick-human-ag.go"
  "silostep-ag.go"
  "teetertotter-ag.go"
  "water-anim-misty-ag.go"
  "wheel-ag.go"
  "windturbine-ag.go"
  "misty-vis.go"
 ))